import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "../contexts/UserContext";
import { FavoritesProvider } from "../contexts/FavoritesContext";

export const metadata: Metadata = {
  title: "insite",
  description: "Generated by create next app",
  icons: {
    icon: "/insite_logo.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Hotjar Tracking Code for https://j13e203.p.ssafy.io/ */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(h,o,t,j,a,r){
                h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                h._hjSettings={hjid:6529392,hjsv:6};
                a=o.getElementsByTagName('head')[0];
                r=o.createElement('script');r.async=1;
                r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                a.appendChild(r);
              })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
            `,
          }}
        />
      </head>
      <body
        className="antialiased"
      >
        <UserProvider>
          <FavoritesProvider>
            {children}
          </FavoritesProvider>
        </UserProvider>
      </body>
    </html>
  );
}
